package com.jgybzx.entity;

import java.io.Serializable;

public class UwExaminationQuestions implements Serializable {
    private String numb;

    public String getNumb() {
        return numb;
    }

    public void setNumb(String numb) {
        this.numb = numb;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uw_examination_questions.ID
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uw_examination_questions.QUESTION_CODE
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    private String questionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uw_examination_questions.QUESTION_CORE_CODE
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    private String questionCoreCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uw_examination_questions.QUESTION_AREA
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    private String questionArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uw_examination_questions.SUBJECT_TYPE
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    private String subjectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uw_examination_questions.REMARK
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uw_examination_questions.QUESTION_CODE_MORE_PRODUCT
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    private String questionCodeMoreProduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uw_examination_questions.QUESTION_DESC
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    private String questionDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uw_examination_questions.ID
     *
     * @return the value of uw_examination_questions.ID
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uw_examination_questions.ID
     *
     * @param id the value for uw_examination_questions.ID
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uw_examination_questions.QUESTION_CODE
     *
     * @return the value of uw_examination_questions.QUESTION_CODE
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public String getQuestionCode() {
        return questionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uw_examination_questions.QUESTION_CODE
     *
     * @param questionCode the value for uw_examination_questions.QUESTION_CODE
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public void setQuestionCode(String questionCode) {
        this.questionCode = questionCode == null ? null : questionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uw_examination_questions.QUESTION_CORE_CODE
     *
     * @return the value of uw_examination_questions.QUESTION_CORE_CODE
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public String getQuestionCoreCode() {
        return questionCoreCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uw_examination_questions.QUESTION_CORE_CODE
     *
     * @param questionCoreCode the value for uw_examination_questions.QUESTION_CORE_CODE
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public void setQuestionCoreCode(String questionCoreCode) {
        this.questionCoreCode = questionCoreCode == null ? null : questionCoreCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uw_examination_questions.QUESTION_AREA
     *
     * @return the value of uw_examination_questions.QUESTION_AREA
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public String getQuestionArea() {
        return questionArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uw_examination_questions.QUESTION_AREA
     *
     * @param questionArea the value for uw_examination_questions.QUESTION_AREA
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public void setQuestionArea(String questionArea) {
        this.questionArea = questionArea == null ? null : questionArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uw_examination_questions.SUBJECT_TYPE
     *
     * @return the value of uw_examination_questions.SUBJECT_TYPE
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public String getSubjectType() {
        return subjectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uw_examination_questions.SUBJECT_TYPE
     *
     * @param subjectType the value for uw_examination_questions.SUBJECT_TYPE
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public void setSubjectType(String subjectType) {
        this.subjectType = subjectType == null ? null : subjectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uw_examination_questions.REMARK
     *
     * @return the value of uw_examination_questions.REMARK
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uw_examination_questions.REMARK
     *
     * @param remark the value for uw_examination_questions.REMARK
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uw_examination_questions.QUESTION_CODE_MORE_PRODUCT
     *
     * @return the value of uw_examination_questions.QUESTION_CODE_MORE_PRODUCT
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public String getQuestionCodeMoreProduct() {
        return questionCodeMoreProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uw_examination_questions.QUESTION_CODE_MORE_PRODUCT
     *
     * @param questionCodeMoreProduct the value for uw_examination_questions.QUESTION_CODE_MORE_PRODUCT
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public void setQuestionCodeMoreProduct(String questionCodeMoreProduct) {
        this.questionCodeMoreProduct = questionCodeMoreProduct == null ? null : questionCodeMoreProduct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uw_examination_questions.QUESTION_DESC
     *
     * @return the value of uw_examination_questions.QUESTION_DESC
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public String getQuestionDesc() {
        return questionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uw_examination_questions.QUESTION_DESC
     *
     * @param questionDesc the value for uw_examination_questions.QUESTION_DESC
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public void setQuestionDesc(String questionDesc) {
        this.questionDesc = questionDesc == null ? null : questionDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", questionCode=").append(questionCode);
        sb.append(", questionCoreCode=").append(questionCoreCode);
        sb.append(", questionArea=").append(questionArea);
        sb.append(", subjectType=").append(subjectType);
        sb.append(", remark=").append(remark);
        sb.append(", questionCodeMoreProduct=").append(questionCodeMoreProduct);
        sb.append(", questionDesc=").append(questionDesc);
        sb.append("]");
        return sb.toString();
    }
}