package com.jgybzx.entity;

import java.util.ArrayList;
import java.util.List;

public class UwExaminationQuestionsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public UwExaminationQuestionsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeIsNull() {
            addCriterion("QUESTION_CODE is null");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeIsNotNull() {
            addCriterion("QUESTION_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeEqualTo(String value) {
            addCriterion("QUESTION_CODE =", value, "questionCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeNotEqualTo(String value) {
            addCriterion("QUESTION_CODE <>", value, "questionCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeGreaterThan(String value) {
            addCriterion("QUESTION_CODE >", value, "questionCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeGreaterThanOrEqualTo(String value) {
            addCriterion("QUESTION_CODE >=", value, "questionCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeLessThan(String value) {
            addCriterion("QUESTION_CODE <", value, "questionCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeLessThanOrEqualTo(String value) {
            addCriterion("QUESTION_CODE <=", value, "questionCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeLike(String value) {
            addCriterion("QUESTION_CODE like", value, "questionCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeNotLike(String value) {
            addCriterion("QUESTION_CODE not like", value, "questionCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeIn(List<String> values) {
            addCriterion("QUESTION_CODE in", values, "questionCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeNotIn(List<String> values) {
            addCriterion("QUESTION_CODE not in", values, "questionCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeBetween(String value1, String value2) {
            addCriterion("QUESTION_CODE between", value1, value2, "questionCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeNotBetween(String value1, String value2) {
            addCriterion("QUESTION_CODE not between", value1, value2, "questionCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCoreCodeIsNull() {
            addCriterion("QUESTION_CORE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andQuestionCoreCodeIsNotNull() {
            addCriterion("QUESTION_CORE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionCoreCodeEqualTo(String value) {
            addCriterion("QUESTION_CORE_CODE =", value, "questionCoreCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCoreCodeNotEqualTo(String value) {
            addCriterion("QUESTION_CORE_CODE <>", value, "questionCoreCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCoreCodeGreaterThan(String value) {
            addCriterion("QUESTION_CORE_CODE >", value, "questionCoreCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCoreCodeGreaterThanOrEqualTo(String value) {
            addCriterion("QUESTION_CORE_CODE >=", value, "questionCoreCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCoreCodeLessThan(String value) {
            addCriterion("QUESTION_CORE_CODE <", value, "questionCoreCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCoreCodeLessThanOrEqualTo(String value) {
            addCriterion("QUESTION_CORE_CODE <=", value, "questionCoreCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCoreCodeLike(String value) {
            addCriterion("QUESTION_CORE_CODE like", value, "questionCoreCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCoreCodeNotLike(String value) {
            addCriterion("QUESTION_CORE_CODE not like", value, "questionCoreCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCoreCodeIn(List<String> values) {
            addCriterion("QUESTION_CORE_CODE in", values, "questionCoreCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCoreCodeNotIn(List<String> values) {
            addCriterion("QUESTION_CORE_CODE not in", values, "questionCoreCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCoreCodeBetween(String value1, String value2) {
            addCriterion("QUESTION_CORE_CODE between", value1, value2, "questionCoreCode");
            return (Criteria) this;
        }

        public Criteria andQuestionCoreCodeNotBetween(String value1, String value2) {
            addCriterion("QUESTION_CORE_CODE not between", value1, value2, "questionCoreCode");
            return (Criteria) this;
        }

        public Criteria andQuestionAreaIsNull() {
            addCriterion("QUESTION_AREA is null");
            return (Criteria) this;
        }

        public Criteria andQuestionAreaIsNotNull() {
            addCriterion("QUESTION_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionAreaEqualTo(String value) {
            addCriterion("QUESTION_AREA =", value, "questionArea");
            return (Criteria) this;
        }

        public Criteria andQuestionAreaNotEqualTo(String value) {
            addCriterion("QUESTION_AREA <>", value, "questionArea");
            return (Criteria) this;
        }

        public Criteria andQuestionAreaGreaterThan(String value) {
            addCriterion("QUESTION_AREA >", value, "questionArea");
            return (Criteria) this;
        }

        public Criteria andQuestionAreaGreaterThanOrEqualTo(String value) {
            addCriterion("QUESTION_AREA >=", value, "questionArea");
            return (Criteria) this;
        }

        public Criteria andQuestionAreaLessThan(String value) {
            addCriterion("QUESTION_AREA <", value, "questionArea");
            return (Criteria) this;
        }

        public Criteria andQuestionAreaLessThanOrEqualTo(String value) {
            addCriterion("QUESTION_AREA <=", value, "questionArea");
            return (Criteria) this;
        }

        public Criteria andQuestionAreaLike(String value) {
            addCriterion("QUESTION_AREA like", value, "questionArea");
            return (Criteria) this;
        }

        public Criteria andQuestionAreaNotLike(String value) {
            addCriterion("QUESTION_AREA not like", value, "questionArea");
            return (Criteria) this;
        }

        public Criteria andQuestionAreaIn(List<String> values) {
            addCriterion("QUESTION_AREA in", values, "questionArea");
            return (Criteria) this;
        }

        public Criteria andQuestionAreaNotIn(List<String> values) {
            addCriterion("QUESTION_AREA not in", values, "questionArea");
            return (Criteria) this;
        }

        public Criteria andQuestionAreaBetween(String value1, String value2) {
            addCriterion("QUESTION_AREA between", value1, value2, "questionArea");
            return (Criteria) this;
        }

        public Criteria andQuestionAreaNotBetween(String value1, String value2) {
            addCriterion("QUESTION_AREA not between", value1, value2, "questionArea");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeIsNull() {
            addCriterion("SUBJECT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeIsNotNull() {
            addCriterion("SUBJECT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeEqualTo(String value) {
            addCriterion("SUBJECT_TYPE =", value, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeNotEqualTo(String value) {
            addCriterion("SUBJECT_TYPE <>", value, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeGreaterThan(String value) {
            addCriterion("SUBJECT_TYPE >", value, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SUBJECT_TYPE >=", value, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeLessThan(String value) {
            addCriterion("SUBJECT_TYPE <", value, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeLessThanOrEqualTo(String value) {
            addCriterion("SUBJECT_TYPE <=", value, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeLike(String value) {
            addCriterion("SUBJECT_TYPE like", value, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeNotLike(String value) {
            addCriterion("SUBJECT_TYPE not like", value, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeIn(List<String> values) {
            addCriterion("SUBJECT_TYPE in", values, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeNotIn(List<String> values) {
            addCriterion("SUBJECT_TYPE not in", values, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeBetween(String value1, String value2) {
            addCriterion("SUBJECT_TYPE between", value1, value2, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeNotBetween(String value1, String value2) {
            addCriterion("SUBJECT_TYPE not between", value1, value2, "subjectType");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeMoreProductIsNull() {
            addCriterion("QUESTION_CODE_MORE_PRODUCT is null");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeMoreProductIsNotNull() {
            addCriterion("QUESTION_CODE_MORE_PRODUCT is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeMoreProductEqualTo(String value) {
            addCriterion("QUESTION_CODE_MORE_PRODUCT =", value, "questionCodeMoreProduct");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeMoreProductNotEqualTo(String value) {
            addCriterion("QUESTION_CODE_MORE_PRODUCT <>", value, "questionCodeMoreProduct");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeMoreProductGreaterThan(String value) {
            addCriterion("QUESTION_CODE_MORE_PRODUCT >", value, "questionCodeMoreProduct");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeMoreProductGreaterThanOrEqualTo(String value) {
            addCriterion("QUESTION_CODE_MORE_PRODUCT >=", value, "questionCodeMoreProduct");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeMoreProductLessThan(String value) {
            addCriterion("QUESTION_CODE_MORE_PRODUCT <", value, "questionCodeMoreProduct");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeMoreProductLessThanOrEqualTo(String value) {
            addCriterion("QUESTION_CODE_MORE_PRODUCT <=", value, "questionCodeMoreProduct");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeMoreProductLike(String value) {
            addCriterion("QUESTION_CODE_MORE_PRODUCT like", value, "questionCodeMoreProduct");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeMoreProductNotLike(String value) {
            addCriterion("QUESTION_CODE_MORE_PRODUCT not like", value, "questionCodeMoreProduct");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeMoreProductIn(List<String> values) {
            addCriterion("QUESTION_CODE_MORE_PRODUCT in", values, "questionCodeMoreProduct");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeMoreProductNotIn(List<String> values) {
            addCriterion("QUESTION_CODE_MORE_PRODUCT not in", values, "questionCodeMoreProduct");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeMoreProductBetween(String value1, String value2) {
            addCriterion("QUESTION_CODE_MORE_PRODUCT between", value1, value2, "questionCodeMoreProduct");
            return (Criteria) this;
        }

        public Criteria andQuestionCodeMoreProductNotBetween(String value1, String value2) {
            addCriterion("QUESTION_CODE_MORE_PRODUCT not between", value1, value2, "questionCodeMoreProduct");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uw_examination_questions
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 25 15:45:26 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}