server:
  port: 8081

spring:
  application:
    name: binary-student
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jgybzx?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useAffectedRows=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  #配置项目热部署 spring.devtools.restart.enabled=true
  devtools:
    restart:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #从spring获取ip
mybatis:
  mapper-locations: classpath:mappers/**
