server:
  port: 8081
spring:
  application:
    name: binary-student
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///jgyzbx?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    name: root
    password: root

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka
#  instance:
#    prefer-ip-address: true #显示ip
#      instance-id: ${spring.cloud.client.ip-address}:${server.port} #从spring获取ip
