spring:
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/jgybzx?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useAffectedRows=true
    url: jdbc:mysql://127.0.0.1:3306/jgybzx?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  #配置项目热部署 spring.devtools.restart.enabled=true
  devtools:
    restart:
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mail:
    host: smtp.163.com
    username: guojy_6526@163.com
    password: WZVWCQHLUDGUIZNL
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465

#  # 邮箱服务器名字
#  spring.mail.host=smtp.163.com
#  # 发送方邮箱地址
#  spring.mail.username=tj_since@163.com
#  # 授权码
#  spring.mail.password=XXX
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true
#  spring.mail.properties.mail.smtp.starttls.required=true

#  # 收件邮箱地址
#  mail.sender.to=1099593012@qq.com
mail:
  sender:
    to: 1325621332@qq.com

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #从spring获取ip
mybatis:
  mapper-locations: classpath:mappers/**

oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  # f8e82172440e87a3f594c1a745b504ee accessKeyId base64编码处理
  accessKeyId: TFRBSTRGemdYUlBxNlpTd21DQng3aTJY
  # c9eb1f6489e1eccbace3f0f146e6686b
  accessKeySecret: d25IekZqaVh4VmxpajE5NWpMSzNTdGlRTExYcm8y
  bucketName: binary-stars
##############################################################################
sendsms:
  accessKeyId: TFRBSTRHNTNCc3NjWVB5bTdZdTlwQmVw
  accessKeySecret: NEtYb3Z6c0lmaGFsZEdiQ1p4b3lucFNpdUdZRFhW
##############################################################################
filter:
  #不需要过滤的请求
  unFilterRequest:
    request1: /student/queryAll.do
jwt:
  key: jgybzx
  failureTime: 3600000








