spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jgybzx?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/**
logging:
  level:
    root: info
    com:
      jgybzx:
        mapper: debug