package com.jgybzx.mapper;

import com.jgybzx.entity.UwExaminationQuestions;
import com.jgybzx.entity.UwExaminationQuestionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UwExaminationQuestionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    long countByExample(UwExaminationQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    int deleteByExample(UwExaminationQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    int insert(UwExaminationQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    int insertSelective(UwExaminationQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    List<UwExaminationQuestions> selectByExampleWithBLOBs(UwExaminationQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    List<UwExaminationQuestions> selectByExample(UwExaminationQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    UwExaminationQuestions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    int updateByExampleSelective(@Param("record") UwExaminationQuestions record, @Param("example") UwExaminationQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") UwExaminationQuestions record, @Param("example") UwExaminationQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    int updateByExample(@Param("record") UwExaminationQuestions record, @Param("example") UwExaminationQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    int updateByPrimaryKeySelective(UwExaminationQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(UwExaminationQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uw_examination_questions
     *
     * @mbg.generated Mon Oct 25 15:45:26 CST 2021
     */
    int updateByPrimaryKey(UwExaminationQuestions record);

    List<UwExaminationQuestions> selectAll();

    void update(@Param("numb") String numb, @Param("id") Integer id);
}